---
exclude: migrations|templates
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
  - repo: https://github.com/myint/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        files: ^app/
        args:
          [
              -i,
              --remove-all-unused-imports,
              --ignore-init-module-imports,
              --expand-star-imports,
              --remove-duplicate-keys
          ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^(app)|(load_testing)/
        args: [ --settings-file, app/pyproject.toml ]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        files: ^(app)|(load_testing)/
        language_version: python3
        args: [ "--config", "app/pyproject.toml" ]

  - repo: https://github.com/radix-ai/auto-smart-commit
    rev: v1.0.2
    hooks:
      - id: auto-smart-commit
        files: ^app/


  - repo: https://github.com/urm8/pyupgrade.git
    rev: 45437ee28e110b9a6ce92af3f58db54187aaf647
    hooks:
      - id: pyupgrade
        files: ^app/
        args: [ --py3-plus, --py36-plus, --py38-plus, --py39-plus, --py310-plus, --keep-runtime-typing]

  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4" # pick a git hash / tag to point to
    hooks:
      - id: flake8
        files: ^app/
        args: [ --config, app/.flake8.cfg, --exit-zero ]
        additional_dependencies:
          - flake8-cognitive-complexity
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-expression-complexity
          - flake8-pie
          - flake8-plugin-utils
          - flake8-print
          - flake8-pytest
          - flake8-pytest-style
          - flake8-simplify
          - flake8-variables-names
