# Generated by Django 5.0.2 on 2024-02-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="label",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Label"),
        ),
    ]
