# Generated by Django 5.0.2 on 2024-02-10 14:32

from django.db import migrations
from wallet.migrations.run_python import generate_wallets

class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_wallet_balance"),
    ]

    operations = [
        migrations.RunPython(generate_wallets.code, reverse_code=migrations.RunPython.noop)
    ]
